/**
 * Palette — Single source of truth for colour values
 *
 * Used by:
 * - opengraph-image.tsx (server-side, can't read CSS vars)
 * - Any server component needing colour values
 *
 * Generated by: scripts/generate-palette.mjs
 * CSS tokens in: src/styles/colour-tokens.css (keep in sync)
 */

export const palette = {
  primary: { oklch: "oklch(60% 0.17 120)", hex: "#748d00" },
  primaryLight: { oklch: "oklch(75% 0.17 120)", hex: "#a1bc1f" },
  primaryMuted: { oklch: "oklch(50% 0.09 120)", hex: "#5d6a2f" },
  accent: { oklch: "oklch(75% 0.14 30)", hex: "#f88b7a" },
  accentMuted: { oklch: "oklch(55% 0.08 30)", hex: "#9c5f55" },
  surface1: { oklch: "oklch(11% 0.01 250)", hex: "#030507" },
  surface2: { oklch: "oklch(15% 0.01 250)", hex: "#070c11" },
  surface3: { oklch: "oklch(23% 0.02 250)", hex: "#161e26" },
  surface4: { oklch: "oklch(29% 0.03 250)", hex: "#222c37" },
  textPrimary: { oklch: "oklch(95% 0.005 120)", hex: "#eeefeb" },
  textSecondary: { oklch: "oklch(75% 0.02 120)", hex: "#acb0a2" },
  textMuted: { oklch: "oklch(55% 0.02 250)", hex: "#69737d" },
} as const;

/** OG image gradients — hex/rgba for Satori compatibility */
export const ogGradients = {
  background: "linear-gradient(150deg, #030507 0%, #070c11 50%, #161e26 100%)",
  glow: "radial-gradient(circle, rgba(116,141,0,0.2) 0%, transparent 60%)",
  accentText: "rgba(248,139,122,0.9)",
  gridLine: "rgba(116,141,0,0.08)",
} as const;

export type PaletteToken = keyof typeof palette;